version: '2'
services:
  pancrease_detection:
    build: .
    shm_size: '32gb'
    ports:
    - 6007:6007/tcp
    volumes:
      - /home/g-skiba/pancreas_new_data/train/imagesTr:/pancreas/train/imagesTr
      #- /home/g-skiba/pancreas_new_data/train/labelsTr:/pancreas/train/bbox3d
      - /home/g-skiba/pancreas_new_data/train/bbox3d:/pancreas/train/bbox3d
      - /home/g-skiba/pancreas_new_data/val/imagesTr:/pancreas/val/imagesTr
      #- /home/g-skiba/pancreas_new_data/val/labelsTr:/pancreas/val/bbox3d
      - /home/g-skiba/pancreas_new_data/val/bbox3d:/pancreas/val/bbox3d
      - /home/g-skiba/pancreas_new_data/inference/imagesTr:/pancreas/inference/imagesTr
      - /home/g-skiba/pancreas_new_data/inference/bbox3d:/pancreas/inference/bbox3d
      - /home/g-skiba/pancreas_new_data/checkpoint_save_dir_f32:/pancreas/checkpoint_save_dir
      - /home/g-skiba/pancreas_new_data/logs_f32:/pancreas/logs
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

